server:
  port: 8087

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: 
      defaultZone: http://localhost:8763/eureka
  instance:
    hostname: localhost
      
spring:
  config:
    import: configserver:http://localhost:8888
  cloud:
    config:
      uri: http://localhost:8888