server:
  port: 8888
  
spring:
  cloud:
    config:
      server:
        default-label: main
        git:
          uri: https://github.com/isabelapiana/microservice-repo
          search-paths: diet, finance, admin, pacient
          
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    auditevents:
      enabled: true
    info:
      enabled: true
  health:
    defaults:
      enabled: true