server:
  port: 8081

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: 
      defaultZone: https://eureka-server-microservice.herokuapp.com/eureka    
  instance:
    homePageUrl: https://eureka-server-microservice.herokuapp.com/
    statusPageUrl: https://microservice--admin.herokuapp.com/actuator/info
    healthCheckUrl: https://microservice--admin.herokuapp.com/actuator/health
    
spring:
  config:
    import: configserver:https://microservice-configserver.herokuapp.com/
  application:
    name: 'admin'