server:
  port: 8081
  
spring:
  datasource:
    url: jdbc:postgresql://database-1.co3n5hj6lnhk.sa-east-1.rds.amazonaws.com:5432/microservice-admin-group2
    username: postgres
    password: postgres153227%
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: postgres
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
    generate-ddl: true
    show-sql: true

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Brazil/East