spring:
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    auditevents:
      enabled: true
    info:
      enabled: true
  health:
    defaults:
      enabled: true